"""Dependency-light mathematical reference implementations."""

from .semantic_core_reference import (
    FrozenDAG,
    FrozenGraphMeasure,
    FrozenProposalGraph,
    GraphMeasure,
    angular_affinity,
    angular_navigation_affinity,
    bounded_quality,
    greedy,
    information_atom,
    lazy_greedy,
    logdet_greedy,
    logdet_value,
    marginal,
    propagate,
    propagate_frozen_graph,
    semantic_atom,
    thin_svd_condition,
    thin_svd_shrink,
)

__all__ = [
    "bounded_quality",
    "angular_affinity",
    "angular_navigation_affinity",
    "FrozenDAG",
    "FrozenProposalGraph",
    "GraphMeasure",
    "FrozenGraphMeasure",
    "propagate",
    "propagate_frozen_graph",
    "thin_svd_shrink",
    "thin_svd_condition",
    "semantic_atom",
    "information_atom",
    "logdet_value",
    "marginal",
    "greedy",
    "logdet_greedy",
    "lazy_greedy",
]
